export type TokenType = 'kw' | 'fn' | 'str' | 'cm' | 'num' | 'tx';

export const TABS = [
  '@execra/sdk · SDK',
  'WebSocket · Any language',
  'MCP · Claude AI',
];

export const CODE: { lang: string; code: { t: TokenType; v: string }[] }[] = [
  {
    lang: 'TypeScript',
    code: [
      { t: 'kw', v: 'import' },
      { t: 'tx', v: ' { AgentWallet } ' },
      { t: 'kw', v: 'from' },
      { t: 'str', v: " '@execra/sdk'\n\n" },
      { t: 'cm', v: '// Finds or creates account by name\n' },
      { t: 'kw', v: 'const ' },
      { t: 'tx', v: 'wallet = ' },
      { t: 'kw', v: 'await ' },
      { t: 'fn', v: 'AgentWallet.connect' },
      { t: 'tx', v: '(' },
      { t: 'str', v: "'Trading Bot'" },
      { t: 'tx', v: ')\n\n' },
      { t: 'cm', v: '// Read\n' },
      { t: 'kw', v: 'const ' },
      { t: 'tx', v: 'balance = ' },
      { t: 'kw', v: 'await ' },
      { t: 'tx', v: 'wallet.' },
      { t: 'fn', v: 'getBalance' },
      { t: 'tx', v: '()\n' },
      { t: 'kw', v: 'const ' },
      { t: 'tx', v: 'txs = ' },
      { t: 'kw', v: 'await ' },
      { t: 'tx', v: 'wallet.' },
      { t: 'fn', v: 'getRecentTransactions' },
      { t: 'tx', v: '(' },
      { t: 'num', v: '10' },
      { t: 'tx', v: ')\n\n' },
      { t: 'cm', v: '// Sign + send (simulates first)\n' },
      { t: 'kw', v: 'const ' },
      { t: 'tx', v: '{ signature, explorerUrl } =\n  ' },
      { t: 'kw', v: 'await ' },
      { t: 'tx', v: 'wallet.' },
      { t: 'fn', v: 'signAndSendTransaction' },
      { t: 'tx', v: '(tx)\n\n' },
      { t: 'cm', v: '// Prove ownership\n' },
      { t: 'kw', v: 'const ' },
      { t: 'tx', v: 'sig = wallet.' },
      { t: 'fn', v: 'signMessage' },
      { t: 'tx', v: '(' },
      { t: 'str', v: "'authenticate'" },
      { t: 'tx', v: ')' },
    ],
  },
  {
    lang: 'Python',
    code: [
      { t: 'kw', v: 'import' },
      { t: 'tx', v: ' websocket, json, base64\n\n' },
      { t: 'tx', v: 'ws = websocket.' },
      { t: 'fn', v: 'create_connection' },
      { t: 'tx', v: '(\n  ' },
      { t: 'str', v: '"ws://localhost:3000/ws/agent"' },
      { t: 'tx', v: '\n)\n\n' },
      { t: 'cm', v: '# Sign and send transaction\n' },
      { t: 'tx', v: 'ws.' },
      { t: 'fn', v: 'send' },
      { t: 'tx', v: '(json.' },
      { t: 'fn', v: 'dumps' },
      { t: 'tx', v: '({\n' },
      { t: 'str', v: '  "id"' },
      { t: 'tx', v: ': 1,\n' },
      { t: 'str', v: '  "jsonrpc"' },
      { t: 'tx', v: ': ' },
      { t: 'str', v: '"2.0"' },
      { t: 'tx', v: ',\n' },
      { t: 'str', v: '  "method"' },
      { t: 'tx', v: ': ' },
      { t: 'str', v: '"solana_signAndSendTransaction"' },
      { t: 'tx', v: ',\n' },
      { t: 'str', v: '  "params"' },
      { t: 'tx', v: ': { ' },
      { t: 'str', v: '"transaction"' },
      { t: 'tx', v: ': tx_b64 },\n' },
      { t: 'str', v: '  "accountName"' },
      { t: 'tx', v: ': ' },
      { t: 'str', v: '"Python Bot"' },
      { t: 'cm', v: '  # routes to keypair\n' },
      { t: 'tx', v: '}))\n\n' },
      { t: 'tx', v: 'result = json.' },
      { t: 'fn', v: 'loads' },
      { t: 'tx', v: '(ws.' },
      { t: 'fn', v: 'recv' },
      { t: 'tx', v: '())\n' },
      { t: 'fn', v: 'print' },
      { t: 'tx', v: '(result[' },
      { t: 'str', v: '"result"' },
      { t: 'tx', v: '][' },
      { t: 'str', v: '"signature"' },
      { t: 'tx', v: '])' },
    ],
  },
  {
    lang: 'JSON config',
    code: [
      { t: 'tx', v: '{\n  ' },
      { t: 'str', v: '"mcpServers"' },
      { t: 'tx', v: ': {\n    ' },
      { t: 'str', v: '"execra"' },
      { t: 'tx', v: ': {\n      ' },
      { t: 'str', v: '"command"' },
      { t: 'tx', v: ': ' },
      { t: 'str', v: '"npx"' },
      { t: 'tx', v: ',\n      ' },
      { t: 'str', v: '"args"' },
      { t: 'tx', v: ': [' },
      { t: 'str', v: '"-y"' },
      { t: 'tx', v: ', ' },
      { t: 'str', v: '"@execra/mcp"' },
      { t: 'tx', v: '],\n      ' },
      { t: 'str', v: '"env"' },
      { t: 'tx', v: ': {\n        ' },
      { t: 'str', v: '"WALLET_PASSWORD"' },
      { t: 'tx', v: ': ' },
      { t: 'str', v: '"your-password"' },
      { t: 'tx', v: '\n      }\n    }\n  }\n}\n\n' },
      { t: 'cm', v: '// Then ask Claude:\n' },
      { t: 'cm', v: '// "Check my Trading Bot balance"\n' },
      { t: 'cm', v: '// "Send 0.1 SOL from Trader to Reporter"' },
    ],
  },
];

export const FEATURES = [
  {
    icon: '🔑',
    title: 'HD Wallet Vault',
    desc: 'BIP-39 mnemonic + BIP-44 derivation. AES-256-GCM encrypted. Compatible with Phantom, Backpack, and Solflare.',
  },
  {
    icon: '⚡',
    title: 'AgentWallet SDK',
    desc: "One-line connect by name. Creates the account if it doesn't exist. Direct vault access or via daemon.",
  },
  {
    icon: '🔌',
    title: 'WebSocket Bridge',
    desc: 'External agents in Python, Rust, Go connect over JSON-RPC. Route to any account by name per-request.',
  },
  {
    icon: '🤖',
    title: 'MCP Server',
    desc: 'Claude AI operates the wallet directly. Natural language to tool calls to signed transactions.',
  },
  {
    icon: '🌐',
    title: 'Chrome Extension',
    desc: 'Registers window.solana via Manifest V3. Works with Jupiter, Magic Eden, any dApp immediately.',
  },
  {
    icon: '🛡️',
    title: 'Pre-flight Simulation',
    desc: 'Every signAndSend simulates on Solana RPC first. Failed simulations never cost a lamport.',
  },
];

export const MCP_TOOLS = [
  ['list_accounts', 'All accounts with addresses'],
  ['create_account', 'Derive a named account'],
  ['get_balance', 'SOL balance by account name'],
  ['transfer_sol', 'Send SOL with simulation'],
  ['request_airdrop', 'Devnet funding'],
  ['simulate_transaction', 'Preview without signing'],
  ['sign_message', 'Prove account ownership'],
  ['get_recent_transactions', 'Transaction history'],
];

export const PACKAGES = [
  {
    name: 'wallet',
    desc: 'AgentWallet SDK. Connect, sign, send, simulate. Works standalone or with the daemon.',
    cmd: 'npm install @execra/sdk',
  },
  {
    name: 'mcp',
    desc: 'MCP server for Claude Desktop and Claude Code. All wallet tools exposed natively.',
    cmd: 'npx -y @execra/mcp',
  },
  {
    name: 'daemon',
    desc: 'Full wallet daemon, vault, WebSocket bridge, WalletConnect v2, CLI dashboard.',
    cmd: 'npm install -g @execra/daemon',
  },
];

export const QUICK_START = ['pnpm install', 'pnpm build', 'pnpm dev'];

export const ROADMAP = [
  {
    status: 'done',
    title: 'Globally installable CLI',
    desc: '@execra/daemon published to npm. Start the daemon with execra init.',
  },
  {
    status: 'done',
    title: 'Standalone MCP package',
    desc: '@execra/mcp published to npm. Add it to Claude Desktop or Claude Code without cloning the repo.',
  },
  {
    status: 'in_progress',
    title: 'x402 support',
    desc: 'Currently being integrated to support x402 payment/auth flows across agent transactions.',
  },
  {
    status: 'planned',
    title: 'Bags API integration',
    desc: 'MCP tools and SDK methods to create, mint, and manage SPL tokens programmatically.',
  },
  {
    status: 'planned',
    title: 'REST API support',
    desc: 'Expose core wallet and agent operations over a REST API after BAGS API integration is complete.',
  },
  {
    status: 'planned',
    title: 'Solana Agent Kit extension',
    desc: 'Adapter for Solana Agent Kit so agents can route signing through the daemon.',
  },
  {
    status: 'planned',
    title: 'AI agent platform integrations',
    desc: 'Integrations with browser-based agent platforms so browser agents can sign natively.',
  },
  {
    status: 'planned',
    title: 'Full wallet UI',
    desc: 'SPL portfolio, transaction history, NFTs, DeFi positions, dApp manager, and custom RPC settings.',
  },
];
